# 1. What are the details of all cars purchased in the year 2022?
Select distinct(s.car_id),make,type,style,cost_$ from sales s left join cars c on s.car_id = c.car_id where purchase_date like '2022%' order by s.car_id

# 2. What is the total number of cars sold by each salesperson?
select salesman_id, count(car_id) as cars_sold from sales group by salesman_id 

# 3. What is the total revenue generated by each salesperson?
select salesman_id, sum(s.car_id * cost_$) as Revenue from sales s left join cars c on s.car_id = c.car_id group by salesman_id

# 4. What are the details of the cars sold by each salesperson?
select salesman_id, c.* from sales s left join cars c on s.car_id = c.car_id order by salesman_id

# 5. What is the total revenue generated by each car type?
select c.type, sum((s.car_id * cost_$)) as Revenue_Generated from sales s left join cars c on s.car_id = c.car_id group by c.type

# 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
select c.* from sales s left join cars c on s.car_id = c.car_id where salesman_id = (select salesman_id from salespersons where name = 'Emily Wong') and Year(purchase_date) = '2021'

# 7. What is the total revenue generated by the sales of hatchback cars?
select c.style, sum((s.car_id * cost_$)) as Revenue_Generated from sales s left join cars c on s.car_id = c.car_id where c.style = 'Hatchback' 

# 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select c.style, sum((s.car_id * cost_$)) as Revenue_Generated from sales s left join cars c on s.car_id = c.car_id where c.style = 'SUV' and year(purchase_date) = '2022'

# 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select name, city from sales s left join salespersons sp on s.salesman_id = sp.salesman_id where year(purchase_date) = '2023' group by s.salesman_id order by count(s.car_id)  desc  limit 1

#10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
select name,age from salespersons sp left join sales s on sp.salesman_id = s.salesman_id left join cars c on s.car_id = c.car_id where year(purchase_date) = '2022' group by name, age order by sum((s.car_id * c.cost_$)) Desc limit 1 

